services:
  funewsmanagementsystem.api:
    image: ${DOCKER_REGISTRY-}funewsmanagementsystemapi
    build:
      context: .
      dockerfile: FUNewsManagementSystem.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=FUNewsDB;User Id=sa;Password=Kenner@hp4;TrustServerCertificate=True;Encrypt=False
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      - sqlserver
    networks:
      - funews-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Kenner@hp4
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - funews-network

networks:
  funews-network:
    driver: bridge

volumes:
  sqlserver-data: